# Generated by Django 3.0.6 on 2020-06-12 14:01

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200606_0147'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='genre',
            managers=[
                ('objets', django.db.models.manager.Manager()),
            ],
        ),
    ]
